# taps repositories
tap caskroom/fonts
tap east301/misc
tap homebrew/completions
tap homebrew/python
tap homebrew/science
tap phinze/cask

# updates formulae & installed packages
update
upgrade

# installs homebrew packages
install brew-cask
install django-completion
install dos2unix
install git
install git-flow
install hg-flow
install nkf
install node
install pstree
install pypy
install python
install python3
install rmtrash
install terminal-notifier
install the_silver_searcher
install tig
install tmux
install tree
install vagrant-completion
install wget

# installs homebrew-cask packages
cask install adobe-reader
cask install adobe-reader-font-packs-asian
cask install airmail
cask install alfred
cask install appcleaner
cask install cyberduck
cask install dropbox
cask install evernote
cask install f-lux
cask install font-source-code-pro
cask install font-vl-gothic
cask install google-chrome
cask install hyokai
cask install intellij-idea-ce
cask install iterm2
cask install java
cask install mono-mdk
cask install mono-mre
cask install mou
cask install netbeans
cask install pycharm-ce
cask install r-app
cask install rstudio
cask install sourcetree
cask install spyder
cask install todoist
cask install totalterminal
cask install vagrant
cask install virtualbox
cask install xamarin-studio
cask install yorufukurou

# cleanup
cleanup
